# Generated by Django 4.0.1 on 2022-02-25 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_emailscheduler_mail_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailscheduler',
            name='mail_time',
            field=models.TimeField(default=datetime.time(19, 10, 13, 537906)),
        ),
    ]
