# Generated by Django 4.0.1 on 2022-02-28 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_emailscheduler_mail_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailscheduler',
            name='mail_time',
            field=models.TimeField(default=datetime.time(11, 40, 13, 456741)),
        ),
    ]
